kodi_apt_repo: "deb http://http.debian.net/debian jessie-backports main"
kodi_user_dir: /home/{{ rpi_user_name }}/.kodi

# Arrays of filepaths
# Inspired by https://github.com/cmprescott/ansible-role-kodi
kodi_source_files: []
kodi_source_music: []
kodi_source_pictures: []
kodi_source_programs: []
kodi_source_videos: []
