kodi_apt_repo: "deb http://pipplware.pplware.pt/pipplware/dists/jessie/main/binary /"
kodi_tvheadend_apt_repo: "deb https://dl.bintray.com/tvheadend/deb {{ ansible_distribution_release }} release"

openbox_config_dir: /home/{{ mc_user_name }}/.config/openbox

# Arrays of filepaths
# Inspired by https://github.com/cmprescott/ansible-role-kodi
kodi_source_files: []
kodi_source_music: []
kodi_source_pictures: []
kodi_source_programs: []
kodi_source_videos: []

with_kodi_buffering: False
kodi_read_buffer_factor: 20
kodi_buffer_size: 139460608

kodi_username: kodi
kodi_user_dir: "/home/{{ kodi_username }}/.kodi"

kodi_allow_reboot: true

kodi_with_tvheadend: false
kodi_tvheadend_username: admin
kodi_tvheadend_password: admin
