---

- name: Configure and securise any Debian server

  hosts: servers
  roles:
    - common

  become: yes

- name: Setup and manage a download server

  hosts: download-servers
  roles:
    - download_server

  become: yes

- name: Setup a media center

  hosts: media-centers
  roles:
    - media_center

  become: yes

- name: Setup a Docker host

  hosts: rpi-dockers
  roles:
    - rpi_docker

  become: yes

- name: Setup a DNS

  hosts: dns-servers
  roles:
    - unbound-role

  become: yes

- name: Setup an Audio Server

  hosts: audio-centers
  roles:
    - audio_center

  become: yes
