---

- name: Configure and securise any Rpi

  hosts: all
  roles:
    - common

  become: yes

- name: Setup and manage a download server

  hosts: download_servers
  roles:
    - download_server

  become: yes
