---

# https://www.prahladyeri.com/blog/2016/02/minimal-debian-desktop-setup.html
- name: Install packages for a minimal desktop
  apt: name={{ item }} state=latest
  with_items:
    - network-manager
    - xorg
    - openbox
    - xdm
    - xbacklight
    - pcmanfm
    - lxappearance
    - lxpanel
    - gmrun
    - gnome-terminal

- name: "Create openbox config directory for {{ server_user_name }}"
  file: path="{{ openbox_config_dir }}" owner="{{ server_user_name }}" group="{{ server_user_name }}" state=directory
  register: create_openbox_config

- name: "Setting up default Openbox config for {{ server_user_name }}"
  shell: cp /etc/xdg/openbox/* "{{ openbox_config_dir }}"
  become: yes
  become_user: "{{ server_user_name }}"
  when: create_openbox_config|changed

- name: Enforce lxpanel opening
  lineinfile: dest="{{ openbox_config_dir }}/autostart"
              regexp="^lxpanel"
              line="lxpanel &"
              create=yes
              state=present
  become: yes
  become_user: "{{ server_user_name }}"
