---

- name: Add Kodi 16 Custom Repo
  apt_repository: repo={{ kodi_apt_repo }}

- name: Add Kodi Repo Key
  apt_key:
    url: "http://pipplware.pplware.pt/pipplware/key.asc"
    state: present

- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install Kodi
  apt: state=installed pkg=kodi force=yes

- name: Add new user for media center
  user:
    name: "{{ kodi_username }}"
    comment: "Kodi session"
    password: "{{ kodi_password_hash }}"
    groups: cdrom,audio,video,plugdev,users,dialout,dip,input,netdev,{{ mc_shared_group }}
    append: yes
    state: present

- name: "Create openbox config directory for {{ kodi_username }}"
  file: path="/home/{{ kodi_username }}/.config/openbox" owner="{{ kodi_username }}" group="{{ kodi_username }}" state=directory
  become: yes
  become_user: "{{ kodi_username }}"

- name: Enforce Kodi opening in standalone mode
  lineinfile: dest="/home/{{ kodi_username }}/.config/openbox/autostart"
              regexp="^/usr/bin/kodi-standalone"
              line="/usr/bin/kodi-standalone &"
              create=yes
              state=present
  become: yes
  become_user: "{{ kodi_username }}"

- name: Create current user configuration directories
  file: path={{ item }} state=directory owner={{ kodi_username }} group={{ kodi_username }} mode=0755
  with_items:
    - "{{ kodi_user_dir }}"
    - "{{ kodi_user_dir }}/userdata"

- name: Build sources file
  template: src=kodi/sources.xml.j2 dest="{{ kodi_user_dir }}/userdata/sources.xml" owner={{ kodi_username }} group={{ kodi_username }} mode=0600

- name: Enable buffering
  template: src=kodi/advancedsettings.xml.j2 dest="{{ kodi_user_dir }}/userdata/advancedsettings.xml" owner={{ kodi_username }} group={{ kodi_username }} mode=0600
  when: with_kodi_buffering
