---

- name: Install Docker custom service
  template: src=docker/docker.service
            dest=/etc/systemd/system/docker.service
            owner=root
            group=root
            mode=0644
  notify: Restart docker

- name: Enable Docker daemon on boot
  service: name=docker enabled=true state=restarted

- name: Install setuptools
  apt: name=python-setuptools state=latest

# Using apt for pip was triggering an ImportError
- name: Install pip
  easy_install: name=pip state=latest

# See https://docs.ansible.com/ansible/guide_docker.html#requirements
- name: Add Ansible required pip packages
  pip: name={{ item.name }} version={{ item.version }} state=present
  with_items:
    - { name: 'docker-py', version: '1.7.0' }
    - { name: 'docker-compose', version: '1.7.0' }
