---

- name: Install librespot required packages
  apt:
    name: '{{ item }}'
    state: latest
  with_items: '{{ ac_required_packages }}'

- name: Set default output to analog (this does not create a conflict with Kodi)
  command: 'amixer -c 0 cset numid=3 1'

- name: Set volume to 100%
  command: "amixer sset 'Master' 100%"
  become: false

# See https://github.com/librespot-org/librespot/wiki/Cross-compiling for
#   instructions to build the binary
- name: 'Copy binary to {{ ac_respot_output_dir }}'
  copy:
    src: '{{ ac_respot_local_binary }}'
    dest: '{{ ac_respot_binary }}'
    owner: root
    group: root
    mode: 0700

- name: Build librespot directory
  file:
    path: '{{ ac_respot_user_dir }}'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
    state: directory

- name: Build cache directory
  file:
    path: '{{ ac_respot_cache_dir }}'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
    state: directory

- name: Install librespot script
  template:
    src: librespot/librespot.sh.j2
    dest: '{{ ac_respot_user_dir }}/librespot.sh'
    owner: root
    group: root
    mode: 0700

- name: Install librespot service
  template:
    src: librespot/librespot.service.j2
    dest: /etc/systemd/system/librespot.service
    owner: root
    group: root
    mode: 0644

- name: Enable librespot on boot
  service: name=librespot enabled=true state=restarted
