---

- name: Install automount packages
  apt: state=installed pkg={{ item }}
  with_items:
    - samba
    - cifs-utils

- name: Create local devices folders
  file: dest=/mnt/{{ item.name }} state=directory mode=0770 group={{ automount_group }}
  with_items: "{{ automount_network_folders }}"

- name: Mount local devices by label
  mount:
    name: "/mnt/{{ item.name }}"
    src: "LABEL={{ item.label }}"
    fstype: "{{ item.type }}"
    state: mounted
  with_items: "{{ automount_local_devices }}"

- name: Create remote folders
  file: dest=/media/{{ item.name }} state=directory mode=0770
  with_items: "{{ automount_network_folders }}"

- name: Mount remote folders
  mount:
    name: "/media/{{ item.name }}"
    src: "{{ item.network_folder }}"
    fstype: "{{ item.type|default('cifs') }}"
    opts: "domain={{ item.domain }},username={{ item.user }},password={{ item.password }},iocharset=utf8,_netdev"
    state: mounted
  with_items: "{{ automount_network_folders }}"
