---

- name: Installing aptitude
  apt:
    name: aptitude
    state: latest

- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrading distribution
  apt: upgrade=yes
  register: upgrade_distribution
  when: server_allow_upgrade

- name: Rebooting server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when:
    - upgrade_distribution|changed
    - server_allow_reboot

- name: Waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  become: false
  when:
    - upgrade_distribution|changed
    - server_allow_reboot

- name: Setup locale
  locale_gen: name={{item}} state=present
  with_items: "{{ server_locales }}"
  register: update_locale

- name: Generate locales
  command: locale-gen
  when: update_locale|changed

- name: Install required packages
  apt: name={{ item }} state=latest
  with_items: "{{ required_packages }}"

- name: Create new server owner
  user: name={{ server_user_name }}
        groups={{ server_user_groups }}
        password={{ server_user_password_hash }}
        shell=/bin/bash
        append=yes
        state=present

- name: Adjust APT update intervals
  template: src=security/apt_periodic dest=/etc/apt/apt.conf.d/10periodic owner=root group=root mode=0644
