---

- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrading distribution
  apt: upgrade=yes
  register: upgrade_distribution

# See https://www.raspberrypi.org/documentation/configuration/config-txt.md
- name: Update boot config for HDMI
  lineinfile: line='hdmi_safe=1'
    dest=/boot/config.txt
    regexp="^hdmi_safe="
    state=present
  register: update_config

- name: Rebooting Rpi
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: (upgrade_distribution|changed) or (update_config|changed)

- name: Waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  become: false
  when: (upgrade_distribution|changed) or (update_config|changed)

- name: Setup locale
  lineinfile: dest=/etc/locale.gen regexp="^#{{item}}" line="{{item}}"
  with_items: "{{ rpi_locale }}"
  register: update_locale

- name: Generate locales
  command: locale-gen
  when: update_locale|changed

- name: Install required packages
  apt: name={{ item }} state=latest
  with_items: "{{ required_packages }}"

- name: Add new group for shared items (downloads and other roles)
  group: state=present name={{ rpi_shared_group }}

- name: Create new Rpi owner
  user: name={{ rpi_user_name }}
        groups={{ rpi_shared_group }},pi,adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi
        password={{ rpi_user_password_hash }}
        shell={{ '/bin/zsh' if with_zsh else '/bin/bash' }}
        append=yes
        state=present

- name: Remove pi user from sudoers
  lineinfile: dest=/etc/sudoers regexp="^pi ALL" state=absent backup=yes

- name: Limit pi's groups
  user: name=pi state=present groups=pi
