---

- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrading distribution
  apt: upgrade=yes

- name: Updating hostname
  hostname: name={{ rpi_host_name }}
  register: hostname_change

- name: Update /etc/hosts (1/2)
  lineinfile: dest=/etc/hosts regexp='^127\.0\.1\.1' line='127.0.0.1	localhost	{{ rpi_host_name }}' owner=root group=root mode=0644 backup=yes

- name: Update /etc/hosts (2/2)
  lineinfile: dest=/etc/hosts regexp='^::1' line='::1		localhost ip6-localhost ip6-loopback	{{ rpi_host_name }}' owner=root group=root mode=0644

- name: Reload facts
  setup:
  when: hostname_change.changed

- name: Setup locale
  lineinfile: dest=/etc/locale.gen regexp="^#{{item}}" line="{{item}}"
  with_items: "{{ rpi_locale }}"
  register: update_locale

- name: Generate locales
  command: locale-gen
  when: update_locale|changed

- name: Install required packages
  apt: state=installed pkg={{ item }}
  with_items: "{{ required_packages }}"

- name: Add new group for shared items (downloads and other roles)
  group: state=present name={{ rpi_shared_group }}

- name: Create new Rpi owner
  user: name={{ rpi_user_name }} groups={{ rpi_shared_group }} password={{ rpi_user_password | password_hash('sha512') }} shell=/bin/zsh append=yes

- name: Add user to sudoers
  lineinfile: dest=/etc/sudoers regexp="{{ rpi_user_name }} ALL" line="{{ rpi_user_name }} ALL=(ALL) ALL" state=present

- name: Clone oh-my-zsh repo
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh
  become: yes
  become_user: "{{ rpi_user_name }}"

- name: Setup default zshrc
  copy: remote_src=true src=~/.oh-my-zsh/templates/zshrc.zsh-template dest=~/.zshrc backup=yes mode=0644
  become: yes
  become_user: "{{ rpi_user_name }}"

- name: Change zsh theme
  lineinfile: dest=~/.zshrc regexp="^ZSH_THEME" line="ZSH_THEME=\"{{ rpi_zsh_theme|default('junkfood') }}\"" state=present
  become: yes
  become_user: "{{ rpi_user_name }}"
