---

- name: Updating hostname (1/2)
  hostname: name={{ rpi_host_name }}
  register: hostname_change

# A second definitive update is needed on certain Rpis
- name: Updating hostname (2/2)
  copy: content: "{{inventory_hostname_short}}{{'\n'}}"
        dest: /etc/hostname
        backup: yes
  register: hostname_change

- name: Update /etc/hosts (IPv4)
  lineinfile: dest=/etc/hosts
              regexp="^127\.0\.1\.1"
              line="127.0.0.1{{'\t'}}{{ rpi_host_name }}{{'\t'}}localhost"
              backup=yes
              state=present

- name: Update /etc/hosts (IPv6)
  lineinfile: dest=/etc/hosts
              regexp="^::1"
              line="::1{{'\t\t'}}{{ rpi_host_name }}{{'\t'}}localhost ip6-localhost ip6-loopback"
              backup=yes
              state=present

- name: Install Zeroconf utilities
  apt: name={{ item }} state=latest
  with_items:
    - libnss-mdns
    - avahi-daemon

- name: Rebooting Rpi
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: hostname_change|changed

- name: Waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  become: false
  when: hostname_change|changed
