---

# Required

- include: base.yml
- include: ssh.yml

- include: hostname.yml
  when: with_custom_hostname

- include: ssmtp.yml

- include: fail2ban.yml
  tags: fail2ban

- include: firewall.yml

- include: unattended-upgrades.yml

- include: logwatch.yml

# Optionnals

- include: wifi.yml
  when: with_wifi
- include: vim.yml
  when: with_vim
- include: mosh.yml
  when: with_mosh
- include: shared_group.yml
  when: server_shared_group is defined
- include: automount.yml
  when: with_automount
- include: zsh.yml
  when: with_zsh

# Super optionnal (may break current process if you're using the user)

- include: user_unsudo.yml server_unsudo_user={{ item }}
  with_items: "{{ server_unsudoed_users }}"
  when: server_unsudoed_users is defined

- include: sudoers_nopasswd.yml
  with_items: "{{ server_sudo_nopasswd_users }}"
  loop_control:
    loop_var: nopasswd_user
  when: server_sudo_nopasswd_users is defined
