---

# Required

- include: base.yml
- include: ssh.yml
- include: firewall.yml

- include: hostname.yml
  when: with_custom_hostname

- include: ssmtp.yml
- include: logwatch.yml

# Optionnals

- include: wifi.yml
  when: with_wifi
- include: vim.yml
  when: with_vim
- include: mosh.yml
  when: with_mosh
- include: shared_group.yml
  when: server_shared_group is defined
- include: automount.yml
  when: with_automount
- include: zsh.yml
  when: with_zsh
