---

- name: Install Mosh
  apt: pkg=mosh state=present

- name: Allow Mosh ports
  ufw: rule=allow port=60000:61000 proto=udp
  notify: Reload firewall

- debug: msg="Remember to use ssh port {{ ssh_port }} in order to establish a mosh connection"
  when: ssh_port is defined
