---

- name: Install SSMTP
  apt: name=ssmtp state=installed

- name: Set up ssmtp.conf
  template: src=ssmtp/ssmtp.conf.j2 dest=/etc/ssmtp/ssmtp.conf

- name: Set up revaliases
  template: src=ssmtp/revaliases.j2 dest=/etc/ssmtp/revaliases
