---

- name: Install aria2 package
  apt: state=installed pkg=aria2

- name: Add new group for download server
  group: state=present name={{ ds_user_group }}

- name: Add new user for download server
  user: name={{ ds_user_name }} group={{ ds_user_group }} comment="Aria2 Download Server" state=present

- name: Make downloads directory
  file: path={{ ds_downloads_directory }} state=directory owner={{ ds_user_name }} group={{ ds_user_group }} mode=0755

- name: Make configuration directory
  file: path=/home/{{ ds_user_name }}/.aria2 state=directory owner={{ ds_user_name }} group={{ ds_user_group }} mode=0755

- name: Copy aria2 configuration
  template: src=aria2/aria2.conf.j2 dest=/home/{{ ds_user_name }}/.aria2/aria2.conf owner={{ ds_user_name }} group={{ ds_user_group }} mode=0600

- name: Install aria2 service
  template: src=aria2/aria2.service dest=/etc/systemd/system/aria2.service owner=root group=root mode=0644
  notify: Restart aria2

- name: Enable aria2 daemon on boot
  service: name=aria2 enabled=true state=started
